# Generated by Django 4.0.4 on 2022-05-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=120, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
