# Generated by Django 4.0.4 on 2022-05-11 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_alter_hint_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
