# Generated by Django 4.0.4 on 2022-05-11 07:12

from django.db import migrations


def set_user_in_themes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Theme = apps.get_model('questions', 'Theme')
    themes = Theme.objects.filter(author=None)
    admin, _ = User.objects.get_or_create(email='admin@mail.com')

    for theme in themes:
        theme.author = admin
        theme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_theme_author_theme_is_private'),
    ]

    operations = [
        migrations.RunPython(set_user_in_themes),
    ]
