version: '3'

services:

  redis:
    container_name: yanki_redis
    image: redis:4-alpine
    volumes:
      - /var/lib/redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    # run in persistent mode
    command: redis-server --appendonly yes
    restart: always

  postgres:
    container_name: yanki_db
    image: postgres:12.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data
    env_file: .env

  backend:
    build:
      dockerfile: .Dockerfile
      context: .
    entrypoint: "wsgi-entrypoint.sh"
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    depends_on:
      - postgres

  frontend:
    build:
      context: ./react-front
      dockerfile: .Dockerfile
    volumes:
      - react_build:/react-front/build

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - react_build:/var/www/react
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/log:/var/log/letsencrypt/
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  react_build:
