version: '3'

services:

  redis:
    container_name: yanki_redis
    image: redis:4-alpine
    volumes:
      - /var/lib/redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    # run in persistent mode
    command: redis-server --appendonly yes
    restart: always

  postgres:
    container_name: yanki_db
    image: postgres:12.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /usr/local/var/postgres:/var/lib/postgresql/data
    env_file: .env

  backend:
    build:
      dockerfile: .Dockerfile
      context: .
    command: gunicorn yanki_cards.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./react-front
      dockerfile: .Dockerfile
    volumes:
      - react_build:/react-front/build

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  react_build:


