version: '3'
services:

  redis:
    container_name: yanki_redis
    image: redis:4-alpine
    volumes:
      - /var/lib/redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    # run in persistent mode
    command: redis-server --appendonly yes
    restart: always

  postgres:
    container_name: yanki_db
    image: postgres:12.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env

  frontend:
    build:
      context: ./react-front
      dockerfile: .Dockerfile
    volumes:
      - react_build:/react-front/build


  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./django-static:/var/www/static
      - react_build:/var/www/react
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  react_build:
