[tool.black]
# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
line-length = 80
target-version = ['py310']
skip-string-normalization = true
include = '\.pyi?$'
extend-exclude = '''
  /(
   | migrations
  )/
'''
