# Generated by Django 4.0.4 on 2022-05-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=60, verbose_name='phrase')),
                ('language', models.CharField(choices=[('en', 'english'), ('ru', 'russian'), ('tr', 'turkish')], default='ru', max_length=2, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.phrase', verbose_name='Phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserWord',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='phrase',
            name='users',
            field=models.ManyToManyField(related_name='phrases', through='words.UserPhrase', to=settings.AUTH_USER_MODEL),
        ),
    ]
