# Generated by Django 4.0.4 on 2022-05-14 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0002_phrase_userphrase_remove_word_users_delete_userword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Created at')),
            ],
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='users',
        ),
        migrations.DeleteModel(
            name='UserPhrase',
        ),
        migrations.AddField(
            model_name='translationsstack',
            name='phrases',
            field=models.ManyToManyField(related_name='translations', to='words.phrase', verbose_name='Phrases'),
        ),
        migrations.AddField(
            model_name='translationsstack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
