# Generated by Django 4.0.4 on 2022-05-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_translationsstack_remove_phrase_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.phrase')),
            ],
        ),
        migrations.RemoveField(
            model_name='translationsstack',
            name='phrases',
        ),
        migrations.AddField(
            model_name='translationsstack',
            name='phrases',
            field=models.ManyToManyField(related_name='translations', through='words.PhraseTranslation',
                                         to='words.phrase', verbose_name='Phrases'),
        ),
        migrations.AddField(
            model_name='phrasetranslation',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.translationsstack'),
        ),
    ]
