# Generated by Django 4.0.4 on 2022-05-18 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_phrasetranslation_alter_translationsstack_phrases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationsstack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
